### ISSUE TITLE
isn't there a bug here, using the same MessageDigest for the private?

### ISSUE THREAD

**Issue by mastern2k3** [richpl/merkletree#1]
https://github.com/richpl/merkletree/blob/95e8eb61845a659eacde21e41e274772c767ea37/src/merkletree/MerkleTree.java#L95

isn't there a bug here?
since you're using the same MessageDigest for the leaf calculation and the node calculation and that the MessageDigest is stateful?

**Comment by richpl** [comment]
I think this is okay. The digest(byte[] input) method is called when completing the node digest calculation, after the updates have been processed. According to the API, "After digest has been called, the MessageDigest object is reset to its initialized state".
